services:
  backend:
    build:
      context: ./backend
    container_name: gemdoc-backend-demo
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env  # Put GEMINI_API_KEY here
    volumes:
      - ./backend:/app
